import Couch from "../assets/Couch.jpg";
import Bike from "../assets/Bike.jpg";
import iPad from "../assets/iPad.jpg";
import Skateboard from "../assets/Skateboard.jpg";
import Textbook from "../assets/Textbook.jpg";

export const SampleProducts = [
  {
    image: Couch,
    productID: "",
    itemName: "New Couch",
    description: "Couch that I bought from IKEA",
    seller: "Parwaz Gill",
    condition: "New",
    location: "Seller Delivers to Buyer",
    listingType: "Bid-And-Buy-Now",
    bidIncrement: "$10",
    currentBid: "$100",
    buyNow: "$250",
    listingPrice: null,
    expirationDate: "2022-11-05T01:20:52.377Z",
    category: "Furniture",
    buying: "Parwaz",
  },
  {
    image: Bike,
    productID: "",
    itemName: "Bike",
    description: "Slightly used bike I got from Walmart",
    seller: "Parwaz Gill",
    condition: "Slightly Used",
    location: "Exchange at Common Point",
    listingType: "Bid-And-Buy-Now",
    bidIncrement: "$15",
    currentBid: "$150",
    buyNow: "$200",
    listingPrice: null,
    expirationDate: "2023-11-05T01:20:52.377Z",
    category: "Transportation",
    buying: "Not Parwaz",
  },
  {
    image: iPad,
    productID: "",
    itemName: "Used iPad",
    description: "Refurbished iPad",
    seller: "Parwaz Gill",
    condition: "Used",
    location: "Buyer Comes to Seller",
    listingType: "Bid-And-Buy-Now",
    bidIncrement: "$25",
    currentBid: "$500",
    buyNow: "$700",
    listingPrice: null,
    expirationDate: "2022-09-05T01:20:52.377Z",
    category: "Electronics",
    buying: "Not Parwaz",
  },
  {
    image: Skateboard,
    productID: "",
    itemName: "Skateboard",
    description: "I've used this product only once before",
    seller: "Parwaz Gill",
    condition: "Like New",
    location: "Seller Delivers to Buyer",
    listingType: "Listing-Only",
    bidIncrement: null,
    currentBid: null,
    buyNow: null,
    listingPrice: "$120",
    expirationDate: "2024-11-05T01:20:52.377Z",
    category: "Transportation",
    sellerID: "Parwaz",
  },
  {
    image: Textbook,
    productID: "",
    itemName: "Unused Textbook",
    description: "Still in packaging, never read",
    seller: "Parwaz Gill",
    condition: "New",
    location: "Seller Delivers to Buyer",
    listingType: "Bid-Only",
    currentBid: "$50",
    bidIncrement: "$5",
    buyNow: null,
    listingPrice: null,
    openBidPrice: "$50",
    expirationDate: "2022-11-13T01:20:52.377Z",
    category: "Books",
    sellerID: "Parwaz",
  },
];
