import Couch from "../assets/Couch.jpg";
import Bike from "../assets/Bike.jpg";
import iPad from "../assets/iPad.jpg";
import Skateboard from "../assets/Skateboard.jpg";
import Textbook from "../assets/Textbook.jpg";

export const SampleProducts = [
  {
    coverImage: Couch,
    secondaryImage1: Couch,
    secondaryImage2: Couch,
    secondaryImage3: Couch,
    secondaryImage4: null,
    productID: "",
    itemName: "New Couch", // up to 32 characters
    description: "Couch that I bought from IKEA", // up to 250 characters
    seller: "Parwaz Gill",
    condition: "New",
    location: "Seller Delivers to Buyer",
    listingType: "Listing Price",
    openingBid: null,
    currentBid: null,
    bidIncrement: null,
    listingPrice: "$300",
    expirationDate: "2022-12-15T01:20:52.377Z",
    category: "Furniture",
    sellerID: "Not Parwaz",
    state: "Inactive",
    role: "Seller",
  },
  {
    coverImage: Bike,
    secondaryImage1: Bike,
    secondaryImage2: Bike,
    secondaryImage3: Bike,
    secondaryImage4: Bike,
    productID: "",
    itemName: "Bike",
    description: "Slightly used bike I got from Walmart",
    seller: "Mason Range",
    condition: "Slightly Used",
    location: "Exchange at Common Point",
    listingType: "Bid Only",
    openingBid: "$125",
    currentBid: null,
    bidIncrement: "$15",
    listingPrice: null,
    expirationDate: "2023-11-10T01:20:52.377Z",
    category: "Transportation",
    sellerID: "Not Parwaz",
    state: "Sold",
    role: "Buyer",
  },
  {
    coverImage: iPad,
    secondaryImage1: null,
    secondaryImage2: iPad,
    secondaryImage3: null,
    secondaryImage4: null,
    productID: "",
    itemName: "Used iPad",
    description: "Refurbished iPad",
    seller: "Mason Range",
    condition: "Used",
    location: "Buyer Comes to Seller",
    listingType: "Bid Only",
    openingBid: "$100",
    currentBid: "$500",
    bidIncrement: "$25",
    listingPrice: null,
    expirationDate: "2022-12-05T01:20:52.377Z",
    category: "Electronics",
    sellerID: "Not Parwaz",
    state: "Evaluating Offers",
    role: "Seller",
  },
  {
    coverImage: Skateboard,
    secondaryImage1: Couch,
    secondaryImage2: Textbook,
    secondaryImage3: Skateboard,
    secondaryImage4: Skateboard,
    productID: "",
    itemName: "Skateboard",
    description: "I've used this product only once before",
    seller: "Mason Range",
    condition: "Like New",
    location: "Seller Delivers to Buyer",
    listingType: "Listing Price",
    openingBid: null,
    currentBid: null,
    bidIncrement: null,
    listingPrice: "$120",
    expirationDate: "2024-12-05T01:20:52.377Z",
    category: "Transportation",
    sellerID: "Not Parwaz",
    state: "Active",
    role: "Buyer",
  },
  {
    coverImage: Textbook,
    secondaryImage1: Textbook,
    secondaryImage2: Textbook,
    secondaryImage3: Textbook,
    secondaryImage4: Textbook,
    productID: "",
    itemName: "Unused Textbook",
    description: "Still in packaging, never read",
    seller: "Parwaz Gill",
    condition: "New",
    location: "Seller Delivers to Buyer",
    listingType: "Bid Only",
    openingBid: "$30",
    currentBid: "$50",
    bidIncrement: "$5",
    listingPrice: null,
    expirationDate: "2022-12-13T01:20:52.377Z",
    category: "Books",
    sellerID: "Parwaz",
    state: "Active",
    role: "Seller",
  },
];
